inputs:
  model_name: 'transposenet'
  mode: 'test'
  backbone_path: './models/backbones/efficient-net-b0.pth'
  dataset_path: '/media/ronf/data/datasets/cambridge'
  labels_file: './datasets/CambridgeLandmarks/abs_cambridge_pose_sorted.csv_ShopFacade_test.csv'
  checkpoint_path: null
  models_path: './out/run_29_09_22_00_09'
  models_to_evaluate: null

general:
  n_freq_print: 1
  n_workers: 4
  device_id: 'cuda:0'

transposenet:
  num_encoder_layers: 4
  dim_feedforward: 256
  hidden_dim: 256
  nheads: 4
  reduction:
    t: 'reduction_4'
    q: 'reduction_3'
  use_prior_t_for_rot: false
  freeze_exclude_phrase: regressor_head_rot