inputs:
  model_name: 'transposenet'
  mode: 'train'
  backbone_path: './models/backbones/efficient-net-b0.pth'
  dataset_path: '/home/dev/Data/7scenes'
  labels_file: './datasets/7Scenes/abs_7scenes_pose.csv_pumpkin_train.csv'
  checkpoint_path: '/media/dev/storage1/transposenet_output/run_08_02_23_07_31/run_08_02_23_07_31_checkpoint-40.pth'
  experiment: null
  output_path: '/media/dev/storage1/transposenet_output'

general:
  n_freq_print: 5
  n_freq_checkpoint: 5 #25 #10
  start_save_epoch: 0 #50 #10
  n_workers: 4
  devices_ids: [0, 1, 2]
  batch_size: 8
  n_epochs: 25 #250 #100

transposenet:
  rot_mode: '6D_GM'
  loss:
    learnable: True
    s_x: -3
    s_q: -6.5
    norm: 2
  lr: 1e-4
  weight_decay: 1e-4
  eps: 1e-10
  lr_scheduler_gamma: 0.75
  lr_scheduler_step_size: 100
  num_encoder_layers: 6
  dim_feedforward: 256
  hidden_dim: 256
  hyper_dim_t: 256
  hyper_dim_rot: 512
  dropout: 0.1
  nheads: 4
  freeze: False
  use_prior_t_for_rot: False
  reduction:
    t: 'reduction_4'
    q: 'reduction_3'
  freeze_exclude_phrase: ['regressor_head_t', 'hypernet_t_fc_h1', 'hypernet_t_fc_h2', 'hypernet_t_fc_o']
#  freeze_exclude_phrase: ['regressor_head_rot', 'hypernet_rot_fc_h1', 'hypernet_rot_fc_h2', 'hypernet_rot_fc_o']