inputs:
  model_name: 'transposenet'
  mode: 'test'
  backbone_path: './models/backbones/efficient-net-b0.pth'
  dataset_path: '/home/dev/Data/cambridge'
  labels_file: './datasets/CambridgeLandmarks/abs_cambridge_pose_sorted.csv_ShopFacade_test.csv'
  checkpoint_path: '/media/dev/storage1/transposenet_output/best_models/cambridge/run_07_01_23_14_52_checkpoint-300.pth'
  models_path: '/media/dev/storage1/transposenet_output/run_25_02_23_19_17'
  models_to_evaluate: null
  experiment: null
  output_path: '/media/dev/storage1/transposenet_output'

general:
  n_freq_print: 5
  n_workers: 4
  devices_id: [0, 1, 2]
  save_hyper_weights_to_file: False

transposenet:
  num_encoder_layers: 6
  dim_feedforward: 256
  hidden_dim: 256
  hyper_dim_t: 256
  hyper_dim_rot: 512
  nheads: 4
  reduction:
    t: 'reduction_4'
    q: 'reduction_3'
  use_prior_t_for_rot: False