inputs:
  model_name: 'transposenet'
  mode: 'test'
  backbone_path: './models/backbones/efficient-net-b0.pth'
  dataset_path: '/home/dev/Data/7scenes'
  labels_file: './datasets/7Scenes/abs_7scenes_pose.csv_pumpkin_test.csv'
  checkpoint_path: null
  models_path: '/media/dev/storage1/transposenet_output/run_08_02_23_18_44'
  models_to_evaluate: null

general:
  n_freq_print: 5
  n_workers: 4
  device_id: 'cuda:0'

transposenet:
  num_encoder_layers: 6
  dim_feedforward: 256
  hidden_dim: 256
  hyper_dim_t: 256
  hyper_dim_rot: 512
  nheads: 4
  reduction:
    t: 'reduction_4'
    q: 'reduction_3'
  use_prior_t_for_rot: False